import type { Metadata } from "next";
import "./globals.css";
import SubNavbar from "@/components/subNavbar";
import Footer from "@/components/Footer";


export const metadata: Metadata = {
  title: "E-commerce",
  description: "Generated by Syed Ali Askari Zaidi",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <SubNavbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
